In [1]:
import numpy as np

Numpy is Numerical Python.  
It is a library consisting of multidimensional array objects and a collection of routines for processing of array.

# Numpy Functions

In [2]:
array1 = np.array([[1,2,3,4],[5,6,7,8]])
array1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# np.zeros

In [3]:

array2 = np.zeros((4,3) , dtype=int)   # Default dtype = float
array2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# np.ones

In [4]:

array3 = np.ones((2,3) , dtype=int)
array3

array([[1, 1, 1],
       [1, 1, 1]])

#  np.arange

In [5]:

array4 = np.arange(6,20,2)
array4

array([ 6,  8, 10, 12, 14, 16, 18])

# random

In [6]:
array6 = np.random.randint(0,25,size=(3,4))
print(array6)

[[ 1  6  9 12]
 [ 8 23 21  7]
 [23 20 24  6]]


# np.full

In [7]:
array7 = np.full((3,2,2),5)
print(array7)

[[[5 5]
  [5 5]]

 [[5 5]
  [5 5]]

 [[5 5]
  [5 5]]]


In [8]:
a = np.random.randint(1,5,(2,4))
a

array([[4, 3, 4, 2],
       [2, 4, 3, 3]])

In [9]:
b = np.random.randint(5,10,(2,4))
b

array([[8, 6, 9, 8],
       [5, 5, 6, 8]])

# divide

In [10]:
divide = np.divide(10,2)
divide

5.0

# multiplication

In [11]:
multiply = np.multiply(186, 200)
multiply

37200

## Aggregation Operations

In [12]:
data = np.random.randint(1,10,(2,4))
data

array([[9, 6, 4, 5],
       [4, 4, 7, 9]])

# add

In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.add(a, b)

In [14]:
c

array([5, 7, 9])

# subtract

In [15]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.subtract(a, b)

In [16]:
c

array([-3, -3, -3])

# Numpy array attributes

#### ndarray.shape
* This returns a tuple consisting of array dimensions.

In [17]:
array_1 = np.array([[1,2,3],[4,5,6]])
print(array_1.shape)

(2, 3)


In [18]:
array_2 = np.array([[[1,2,3],[4,5,6]],
                       [[1,2,3],[4,5,6]],
                       [[1,2,3],[4,5,6]],
                       [[1,2,3],[4,5,6]]])
print(array_2.shape)

(4, 2, 3)


#### ndarray.ndim
* This returns the number of array dimensions.

In [19]:
array_3 = np.array([[1,2,3],[4,5,6]])
print(f"The dimension of array_3: ",array_3.ndim)

The dimension of array_3:  2


#### ndarray.size
* This returns the total number of elements in the array

In [20]:
array_4 = np.array([[1,2,3],[4,5,6]])
print(f"The total number of elements in array_4 =  {array_4.size}")

The total number of elements in array_4 =  6


#### ndarray.dtype
* This returns the data type of the array


In [21]:
array_5 = np.array([1,2,3,4,5])
print(array_5.dtype)

int32


In [22]:
array_6 = np.array([1,2,3,4,5,5.678,-6])
print(array_6.dtype)

float64


#### ndarray.astype
* This changes the data type of an array.

In [23]:
array_7 = np.array([2,3,4])
print(array_7.dtype)
print(array_7)
array_7_ = array_7.astype('float64')
print(array_7_.dtype)
print(array_7_)

int32
[2 3 4]
float64
[2. 3. 4.]


## Array Manipulation

#### np.transpose(array)

In [24]:
array_8 = np.array(np.random.randint(1,6,(6,2)))
array_8

array([[2, 5],
       [1, 1],
       [1, 1],
       [2, 2],
       [2, 2],
       [3, 1]])

In [25]:
transpose_arr = np.transpose(array_8)
transpose_arr

array([[2, 1, 1, 2, 2, 3],
       [5, 1, 1, 2, 2, 1]])